//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOAT_RESTAURANT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public System.TimeSpan ReservationTime { get; set; }
        public int NumGuests { get; set; }
        public string SpecialRequests { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
